[WebAdmin]
# 云运动 Docker Web 控制台的超级管理员账号和密码（请务必修改后再启动）
username = admin
password = admin

[QQBot]
# (Reverse WebSocket模式，通信端主动连接服务端的 /ws/qqbot 即可)
access_token = 

[TGBot]
# 填写Telegram Bot的访问令牌（留空则不开启此推送通道）
token = 
# 代理配置：支持 http/socks5，如 http://127.0.0.1:7890
# 如果代理需要账号密码，格式为：http://user:password@host:port
proxy = 

[Yun]
school_host = http://47.99.163.239:8080
publickey = BDdKFsuBf51UObke1pEgfER17biBg/5r8slqE4s8oOa8lVesWgIUxsRc+AmZ72GcuJ56f7avnyJe3CJY4n00LU4=
privatekey = P3s0+rMuY4Nt5cUWuOCjMhDzVNdom+W0RvdV6ngM+/E=
cipherkeyencrypted = BGfbsG9EkXz5KeCva8E0MisBeS6bhBEDId3VXeIuBoiBMZU0Mosv7PqKsvqxZ3PjkUlsjzh09Se629SWW45XP4TIUeXoLpYzgk5fAMbg0VNVnXuLH9xVzdHAeM+1qJrgvwwkwio85/DnrP1aArvVQrw3N4xd5tugqQ==
cipherkey = JXhWGZjmhhXN+nt8nLpNxA==
md5key = pie0hDSfMRINRXc7s1UIXfkE
platform = android
app_edition = 3.5.1
school_login_url = appLogin
school_id = 195
school_name = 安徽邮电职业技术学院

[Run]
# 跑步核心参数（由调度器 tasks.py 使用）
single_mileage_min_offset = 0.5
single_mileage_max_offset = -0.5
cadence_min_offset = 30
cadence_max_offset = -150
split_count = 10
strides = 0.8
