[WebAdmin]
# 云运动 Docker Web 控制台的超级管理员账号和密码（请务必修改后再启动）
username = admin
password = admin

[QQBot]
# (Reverse WebSocket模式，通信端主动连接服务端的 /ws/qqbot 即可)
access_token = 

[Yun]
yun_host = https://sports.yzhiee.com:8085
school_host = http://47.99.163.239:8080
publickey = BDdKFsuBf51UObke1pEgfER17biBg/5r8slqE4s8oOa8lVesWgIUxsRc+AmZ72GcuJ56f7avnyJe3CJY4n00LU4=
privatekey = P3s0+rMuY4Nt5cUWuOCjMhDzVNdom+W0RvdV6ngM+/E=
cipherkeyencrypted = BGfbsG9EkXz5KeCva8E0MisBeS6bhBEDId3VXeIuBoiBMZU0Mosv7PqKsvqxZ3PjkUlsjzh09Se629SWW45XP4TIUeXoLpYzgk5fAMbg0VNVnXuLH9xVzdHAeM+1qJrgvwwkwio85/DnrP1aArvVQrw3N4xd5tugqQ==
cipherkey = JXhWGZjmhhXN+nt8nLpNxA==
md5key = pie0hDSfMRINRXc7s1UIXfkE
platform = android
app_edition = 3.5.1
school_login_url = appLogin
school_id = 195
school_name = 安徽邮电职业技术学院

[Run]
exclude_points = ["117.209175,31.774432","117.208173,31.774737","117.208326,31.774448","117.206983,31.774748"]
min_distance = 2.5
allow_overflow_distance = 0.1
single_mileage_min_offset = 0.5
single_mileage_max_offset = -0.5
cadence_min_offset = 30
cadence_max_offset = -150
split_count = 10
min_consume = 4.50
max_consume = 5.50
strides = 0.8
drift_enable = true
drift_max_points = 5 
drift_radius_low = 0.00002
drift_radius_high = 0.00008

[Scheduler]
# 指定不执行自动排队的星期几(0代表周一，6代表周日。逗号分隔，缺省为空。如 5,6 表示周六周日不跑)
exclude_weekdays = 5,6
# 指定不执行自动排队的法定节假日额外日期(格式 MMDD 逗号分隔，如 0101,0501,1001)
exclude_dates = 0101,0501,1001

[TGBot]
# 填写Telegram Bot的访问令牌（留空则不开启此推送通道）
token = 
