version: '3.8'

services:
  yun_web:
    build: .
    container_name: yun_runner
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./config.ini:/app/config.ini
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
