version: '3.8'

services:
  yun_web:
    build: .
    container_name: yun_runner
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
      - ./config.ini:/app/config.ini
      - ./tasks_else:/app/tasks_else
      - ./tasks_fch:/app/tasks_fch
      - ./tasks_txl:/app/tasks_txl
      - ./tasks_xc:/app/tasks_xc
    environment:
      - TZ=Asia/Shanghai
