"""Initial commit

Revision ID: 5ee7c9cbab35
Revises: 
Create Date: 2026-04-20 11:02:26.685186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee7c9cbab35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('qq_number', sa.String(), nullable=True),
    sa.Column('qq_notify_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_groups_id'), 'push_groups', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('yun_username', sa.String(), nullable=True),
    sa.Column('yun_password', sa.String(), nullable=True),
    sa.Column('yun_token', sa.String(), nullable=True),
    sa.Column('qq_number', sa.String(), nullable=True),
    sa.Column('qq_notify_type', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('school_host', sa.String(), nullable=True),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('sys_edition', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('push_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['push_group_id'], ['push_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_logs_id'), 'run_logs', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_time', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('run_days', sa.String(length=50), nullable=True),
    sa.Column('route_type', sa.String(), nullable=True),
    sa.Column('random_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('last_run_status', sa.String(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_group_id'), 'schedules', ['group_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_group_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_run_logs_id'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_push_groups_id'), table_name='push_groups')
    op.drop_table('push_groups')
    # ### end Alembic commands ###
