"""add_system_config_table

Revision ID: a2c0146072e4
Revises: 5ee7c9cbab35
Create Date: 2026-04-25 01:46:32.893568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c0146072e4'
down_revision: Union[str, None] = '5ee7c9cbab35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('web_admin_username', sa.String(), nullable=True),
    sa.Column('web_admin_password', sa.String(), nullable=True),
    sa.Column('qq_bot_access_token', sa.String(), nullable=True),
    sa.Column('tg_bot_token', sa.String(), nullable=True),
    sa.Column('tg_bot_proxy', sa.String(), nullable=True),
    sa.Column('yun_public_key', sa.String(), nullable=True),
    sa.Column('yun_private_key', sa.String(), nullable=True),
    sa.Column('yun_cipherkey', sa.String(), nullable=True),
    sa.Column('yun_cipherkey_encrypted', sa.String(), nullable=True),
    sa.Column('yun_md5key', sa.String(), nullable=True),
    sa.Column('yun_platform', sa.String(), nullable=True),
    sa.Column('yun_app_edition', sa.String(), nullable=True),
    sa.Column('yun_school_login_url', sa.String(), nullable=True),
    sa.Column('run_single_mileage_max_offset', sa.String(), nullable=True),
    sa.Column('run_cadence_min_offset', sa.String(), nullable=True),
    sa.Column('run_cadence_max_offset', sa.String(), nullable=True),
    sa.Column('run_split_count', sa.Integer(), nullable=True),
    sa.Column('run_strides', sa.String(), nullable=True),
    sa.Column('run_enable_coord_drift', sa.Boolean(), nullable=True),
    sa.Column('run_enable_duration_random', sa.Boolean(), nullable=True),
    sa.Column('run_enable_cadence_random', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
